web:
  container_name: web
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./:/lorica
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  container_name: php-fpm
  image: nanoninja/php-fpm:latest
  volumes:
    - ./:/lorica
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    - maildev

mysql:
  container_name: mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

maildev:
  container_name: maildev
  image: djfarrelly/maildev
  ports:
   - "8081:80"

wpcli:
  container_name: wpcli
  image: fiskhandlarn/wpcli
  volumes:
    - ./:/lorica
    - ./:/var/www/html
  links:
    - mysql:db
  environment:
    WORDPRESS_DB_PASSWORD: password
