web:
  container_name: web
  image: nginx:latest
  ports:
    #- "8080:80"
    - "3000:443"
  volumes:
    - ./:/lorica
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/.ssl:/ssl
  links:
    - php

php:
  container_name: php-fpm
  image: nanoninja/php-fpm:latest
  volumes:
    - ./:/lorica
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql

mysql:
  container_name: mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - ./.docker/.mysql-data:/var/lib/mysql

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

wpcli:
  container_name: wpcli
  image: fiskhandlarn/wpcli
  volumes:
    - ./:/lorica
  links:
    - mysql:db
  environment:
    WORDPRESS_DB_PASSWORD: password
