# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container
      #- image: quay.io/pantheon-public/build-tools-ci:1.x
      # for screenshots
      - image: selenium/standalone-chrome:3
      # visual regression testing
      - image: backstopjs/backstopjs

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install

      - run:
          name: build
          command: |
            npm run prod

      - run:
          name: run backstop
          command: |
            ./node_modules/backstopjs/cli/index.js test
