# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:

      # visual regression testing
      - image: backstopjs/backstopjs

    working_directory: ~/

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install

      - run:
          name: run our tests
          command: |
            npm run prod
            ./node_modules/backstopjs/cli/index.js test
