# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:

      # visual regression testing
      - image: backstopjs/backstopjs
      # Specify the version you desire here
      #      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install

      - run: docker run --rm -v $(pwd):/src backstopjs/backstopjs --version

      - run:
          name: run our tests
          command: |
            npm run prod
            backstopjs test
